
apiVersion: v1
kind: Service
metadata:
  name: resources-app-service
  labels:
    app: resources-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
  type: NodePort
  selector:
    app: resources-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-app
  namespace: k8s-program
  labels:
    app: resources-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-app
  template:
    metadata:
      labels:
        app: resources-app
    spec:
      containers:
        - name: resources-app
          image: docker.io/epamvaleriynechayev/resources-app:2.0
          ports:
            - containerPort: 8080
# probes
          startupProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2

# variables
          env:
            - name: RESOURCES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: DB_USER
            - name: RESOURCES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apps-secrets
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: resources-app-configmap


