apiVersion: v1
kind: Service
metadata:
  name: songs-app-service
  labels:
    app: songs-app
spec:
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
      protocol: TCP
  type: NodePort
  selector:
    app: songs-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-app
  namespace: k8s-program
  labels:
    app: songs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-app
  template:
    metadata:
      labels:
        app: songs-app
    spec:
      containers:
        - name: songs-app
          image: docker.io/epamvaleriynechayev/songs-app:1.0
          ports:
            - containerPort: 8081
          env:
            - name: RESOURCES_MS_PORT
              value: "8080"
            - name: RESOURCES_DB_URL
              value: postgres-service
            - name: RESOURCES_DB_PORT
              value: "5432"
