apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-stateful-set
spec:
  selector:
    matchLabels:
      app: database
  serviceName: postgres-service
  replicas: 1
#  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: database
    spec:
#      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-db-pv
              mountPath: /data
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/init-script/init-script.sql"]
      volumes:
        - name: init_sql_script
          configMap:
            name: script-configmap
  volumeClaimTemplates:
    - metadata:
        name: postgres-db-pv
      spec:

        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
