apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: db-pv
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-persistent-volume-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pv
  template:
    metadata:
      labels:
        app: db-pv
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: manual-pv
              mountPath: /data
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
      volumes:
        - name: manual-pv
          persistentVolumeClaim:
            claimName: manual-pvc

